### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
… as discussed in #1. A few hints along:

* you can build upon this by e.g. adding a featureGraphic or per-release changelogs. Be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance with that (and please pay attention to the limitations, especially such as "max 80 chars for short description, 4000 chars for full description, 500 chars for per-release changelogs, as those are otherwise cut off at the mentioned position – even if it's mid-word)
* the full description shipped with this PR is "HTML all put on a single line". Background for that is F-Droid (server/client) replaces `\n` by `<br>` which might destroy formatting by introducing "additional empty lines"; this type of format prevents that. My updater would take care for that should you switch to "multi-line", F-Droid.org won't. With my repo, you could even use Markdown there – but then should send me an "advance notice" so I make sure it handles it as such.
* Some hints on formatting full-description can also be found in [my Wiki on Fastlane formattings](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane)

As indicated: My updater will check your fastlane tree whenever it pulls the APK from a new release, and take changes (updated/newer files) along. And if there are any questions left, just ask :smiley:

Now: Enjoy! I'm meanwhile looking forward to maybe seeing [my badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) showing up with the install instructions :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by stsaz** [comment]
Great! Will merge soon.
My only concern is that I need to keep screenshot files inside the main branch.  Although it would be better if we could place them inside another branch (because it's easy to `git push --force` there), but I don't mind for now.
Perhaps the use of git submodules would help with this, but it seems like a too complex solution for this little problem...

> ...which might destroy formatting by introducing "additional empty lines"; this type of format prevents that

Will keep in mind.

> With my repo, you could even use Markdown there

.md would be the best, indeed.  However, it's also easy to break something visually, unless your rendering exactly matches the one GitHub uses, so for the best portability html is better in this case, is it not?

> I'm meanwhile looking forward to maybe seeing my badge showing up with the install instructions 

Yeah, the best place for it is inside `Install.Android` section.
So I will copy https://gitlab.com/IzzyOnDroid/repo/-/raw/master/assets/IzzyOnDroid.png somewhere (e.g. into `res/`) and link it to `https://apt.izzysoft.de/packages/com.github.stsaz.phiola` -- is this correct?

I also saw that there's an option to use a png file from Shields.io, but I don't want to directly use an image from an external site (who knows what they can return).

**Comment by IzzySoft** [comment]
> My only concern is that I need to keep screenshot files inside the main branch.

For my repo, it should work with a branch. If you want to give that a try, we can do that. Just for F-Droid.org, should you want to go there one day, it must be available at the commit the tag points to.

> unless your rendering exactly matches the one GitHub uses

It does not. Github uses Github flavored markdown, my repo uses "standard markdown" while supporting MarkdownExtra.

> So I will copy

Wherever you like, yes. I don't mind "deeplinking" it from GitLab, your choice. Keeping a "local" copy makes sure you're in control – using a deeplink makes sure you always have the latest version. Not that I plan to change that one, no reason to do that :laughing:

> I also saw that there's an option to use a png file from Shields.io

Up to you. You can pick one, or use both – whatever you prefer.

**Comment by stsaz** [comment]
> For my repo, it should work with a branch.

I think the next time I'll need to update screenshots we can try this, but for now it's ok.

I updated readme file - there's a link to your site now!  In case your icon/badge is modified in the future, please send me a note - I will update it on my side.

Thank you for contribution!

**Comment by IzzySoft** [comment]
> I think the next time I'll need to update screenshots we can try this, but for now it's ok.

Should you change it (e.g. to a branch) please let me know. I need to update the location then on my end (and see if it works).

> I updated readme file - there's a link to your site now!

Cool, thanks!

> In case your icon/badge is modified in the future, please send me a note

A change is unlikely to happen. And I'm afraid I would not remember whom to notify then – with more than 1.1k apps in my repo…

> Thank you for contribution!

Gladly done – thanks for accepting it! Helps both of us – and everyone using my repo :smiley:

**Pull request closed without merging**
